### ISSUE TITLE
Dependencies aren't installed automatically by pip

### ISSUE THREAD

**Issue by markusbkoch** [BlockScience/cadCAD#70]
From the cadCAD Telegram group

> **Stephen Young**
> Hey guys, just did a clean install of anaconda and then did pip install cadCAD
> Running the first tutorial I had to manually install the following modules: fn
> funcy
> pathos
> Wasn't an issue, just did a pip install for each. I'm quite new to python but seems like missing dependency config somewhere?

**Comment by JEJodesty** [comment]
Hay is it possible to link this issue to your PR?

**Comment by markusbkoch** [comment]
#69 is the PR meant to fix this. I believe the issue will be closed automatically when it's merged into `master`?

**Comment by markusbkoch** [comment]
Fixed @ 9f96821b898967cfb93deb796c22fdc99301b5f9
